/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: 3b57fbf7f76e59dd0d1c414785f27b53)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	WORKOS_CLIENT_ID: string;
	WORKOS_ISSUER: string;
	STRIPE_CREATOR_MONTHLY_PRICE_ID: string;
	STRIPE_CREATOR_ANNUAL_PRICE_ID: string;
	STRIPE_PRO_MONTHLY_PRICE_ID: string;
	STRIPE_PRO_ANNUAL_PRICE_ID: string;
	STRIPE_PORTAL_CONFIGURATION_ID: string;
	BILLING_RETURN_URL: string;
	CORTEX_AI_ENABLED: string;
	AI_PROVIDER_ENABLED: string;
	CORTEX_FREE_ONLY: string;
	STRIPE_RECONCILE_AFTER_SECONDS: string;
	CORTEX_ADMIN_WORKOS_USER_IDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORKOS_CLIENT_ID" | "WORKOS_ISSUER" | "STRIPE_CREATOR_MONTHLY_PRICE_ID" | "STRIPE_CREATOR_ANNUAL_PRICE_ID" | "STRIPE_PRO_MONTHLY_PRICE_ID" | "STRIPE_PRO_ANNUAL_PRICE_ID" | "STRIPE_PORTAL_CONFIGURATION_ID" | "BILLING_RETURN_URL" | "CORTEX_AI_ENABLED" | "AI_PROVIDER_ENABLED" | "CORTEX_FREE_ONLY" | "STRIPE_RECONCILE_AFTER_SECONDS" | "CORTEX_ADMIN_WORKOS_USER_IDS">> {}
}
